- name: install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: epel-release
  yum:
    name: epel-release
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Install Docker
  yum: 
    name: docker-ce
    state: latest

- name: Install Docker
  tags: compose
  yum: 
    name: docker-compose
    state: latest

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Make sure the service is running
  systemd:
    state: started
    name: docker
